server:
  port: 8080
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fs_system?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: mysql84  # 修改为实际密码
    
logging:
  level:
    root: INFO
    com.fs.system: INFO
  file:
    name: C:/fs_system/logs/fs-system.log